---
- hosts: icx
  gather_facts: yes
  vars:
    ansible_network_os: icx
    ansible_become: True
    ansible_user: alethea
    ansible_password: alethea123
    ansible_become_method: enable
    ansible_become_pass: alethea123
    # ansible_python_interpreter: /usr/bin/python3.5
    # ansible_persistent_log_messages: True
    
        
  tasks:
  - name: configure static route with purge
    icx_static_route6:
      prefix: 2001:0000:3238:DFE1:0063:0000:0000:FEFB/128
      next_hop: 2001:0000:3238:DFE1:0063:0000:0000:FEFB
      state: present
      purge: True
    
  # - name: configure static route with purge (compressed ip)
  #   icx_static_route6:
  #     prefix: "6666:1:1::/64"
  #     next_hop: "6666:1:1::"
  #     state: present
  #     # purge: True

  # - name: configure static route with admin_distance
  #   icx_static_route6:
  #     prefix: 2001:0000:3238:DFE1:0063:0000:0000:FEFB/128
  #     next_hop: 2001:0000:3238:DFE1:0063:0064:0000:FEFB
  #     state: present
  #     admin_distance: 5
  
  # - name: configure static route with distance (compressed ip)
  #   icx_static_route6:
  #     prefix: "6666:1:1::/64"
  #     next_hop: "6666:1:2::"
  #     admin_distance: 5
  #     state: present

  # - name: configure static route with state=absent
  #   icx_static_route6:
  #     prefix: 2001:0000:3238:DFE1:0063:0000:0000:FEFB/128
  #     next_hop: 2001:0000:3238:DFE1:0063:0064:0000:FEFB
  #     state: absent
  #     admin_distance: 5

  # - name: configure static route with state=absent
  #   icx_static_route6:
  #     prefix: "6666:1:1::/64"
  #     next_hop: "6666:1:2::"
  #     admin_distance: 5
  #     state: absent

  # - name: configure static route with check_running_config True
  #   icx_static_route6:
  #     prefix: 2001:0000:3238:DFE1:0063:0000:0000:FEFB/128
  #     next_hop: 2001:0000:3238:DFE1:0063:0000:0000:FEFB
  #     state: present
  #     check_running_config: True

  # - name: configure static route (Duplicate route check_running_config True (compressed ip)
  #   icx_static_route6:
  #     prefix: "6666:1:1::/64"
  #     next_hop: "6666:1:1::"
  #     state: present
  #     check_running_config: True

  # - name: configure static route with check_running_config False
  #   icx_static_route6:
  #     prefix: 2001:0000:3238:DFE1:0063:0000:0000:FEFB/128
  #     next_hop: 2001:0000:3238:DFE1:0063:0000:0000:FEFB
  #     state: present
  #     check_running_config: False
    
  # - name: configure static route (Duplicate route check_running_config False (compressed ip)
  #   icx_static_route6:
  #     prefix: 6666:1:1::/64
  #     next_hop: "6666:1:1::"
  #     state: present
  #     check_running_config: False

  # - name: aggregate config
  #   icx_static_route6:
  #    aggregate:
  #     - prefix: 2001:0000:3238:DFE1:0063:0000:0000:FEFB/108
  #     - prefix: 2001:0000:3238:DFE1:0063:0000:0000:FEFB/64
  #    next_hop: 2001:0000:3238:DFE1:0063:0064:0000:FEFB
  #    state: present
  
  # - name: aggregate config with individual next_hop
  #   icx_static_route6:
  #    aggregate:
  #     - prefix: 6666:1:12::0/64
  #       next_hop: 6666:1:4::0 
  #     - prefix: 6666:1:13::0/64 
  #       next_hop: 6666:1:3::0
  #    admin_distance: 30
  #    state: present

  # - name: aggregate config
  #   icx_static_route6:
  #    aggregate:
  #     - prefix: 2001:0000:3238:DFE1:0063:0000:0000:FEFB/108
  #     - prefix: 2001:0000:3238:DFE1:0063:0000:0000:FEFB/64
  #    next_hop: 2001:0000:3238:DFE1:0063:0064:0000:FEFB
  #    state: absent

  # - name: aggregate config state = present
  #   icx_static_route6:
  #    aggregate:
  #     - prefix: 6666:1:12::0/64
  #       next_hop: 6666:1:4::0 
  #     - prefix: 6666:1:13::0/64 
  #       next_hop: 6666:1:3::0
  #    admin_distance: 30
  #    state: absent


  # - name: aggregate config state = present
  #   icx_static_route6:
  #    aggregate:
  #     -  prefix: 2001:0000:3238:DFE1:0063:0000:0000:FEFB/32
  #        next_hop: 2001:0000:3238:DFE1:0064:0063:0000:FEFB
  #     -  prefix: 2001:0000:3238:DFE1:0063:0000:0000:FEFB/64 
  #     -  prefix: 2001:0000:3238:DFE1:0063:0000:0000:FEFB/108
  #    next_hop: 2001:0000:3238:DFE1:0064:0000:0000:FEFB
  #    admin_distance: 30
  #    state: present
    
    register: output
      
  - debug:
     msg: '{{ output }}'
      
      
